// types alias corressponding to field names
export type Inputs = {
    firstName: string,
    lastName: string,
    admissionDate: string,
    planned: string,
    itemNumber: string,
    pFirstName: string,
    pLastName: string,
    dateOfBirth: string,
    gender: string,
    maritalStatus: string,
    ageValidation: string,
    pgFirstName: string,
    pgLastName: string,
    employment: string,
    phoneNumber: string,
    email: string,
    addr1: string,
    addr2: string,
    city: string,
    state: string,
    zipcode: string,
}
